//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonateNeedyDesignNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonation
    {
        public int donationID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> statusID { get; set; }
        public string donationAmount { get; set; }
        public string emailID { get; set; }
        public string name { get; set; }
        public string comments { get; set; }
        public string transactionChargeS { get; set; }
        public string receivedAmount { get; set; }
        public string transactionID { get; set; }
        public string currency { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> donationTypeID { get; set; }
        public Nullable<int> registrationID { get; set; }
        public Nullable<bool> emailnotification { get; set; }
        public Nullable<bool> anonymusdonor { get; set; }
        public Nullable<bool> anonymusname { get; set; }
    
        public virtual tblDonationType tblDonationType { get; set; }
        public virtual tblEvent tblEvent { get; set; }
        public virtual tblRegistration tblRegistration { get; set; }
        public virtual tblStatu tblStatu { get; set; }
    }
}
