//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonateNeedyDesignNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvent()
        {
            this.tblCharities = new HashSet<tblCharity>();
            this.tblDonations = new HashSet<tblDonation>();
        }
    
        public int EventID { get; set; }
        public int registrationID { get; set; }
        public string Title { get; set; }
        public int categoryID { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Venue { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> confirmed { get; set; }
        public string targetAmount { get; set; }
        public string collectedAmount { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string reasonForRejecting { get; set; }
        public Nullable<bool> Approval { get; set; }
        public string Video { get; set; }
        public string BenificiaryType { get; set; }
        public string OrganiserName { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCharity> tblCharities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDonation> tblDonations { get; set; }
        public virtual tblRegistration tblRegistration { get; set; }
    }
}
