//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonateNeedyDesignNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRegistration()
        {
            this.tblAuthentications = new HashSet<tblAuthentication>();
            this.tblContactUs = new HashSet<tblContactU>();
            this.tblDonations = new HashSet<tblDonation>();
            this.tblEmailTemplateSaves = new HashSet<tblEmailTemplateSave>();
            this.tblErrorlogs = new HashSet<tblErrorlog>();
            this.tblEvents = new HashSet<tblEvent>();
            this.tblSubscribes = new HashSet<tblSubscribe>();
            this.tblTestimonials = new HashSet<tblTestimonial>();
        }
    
        public int registrationID { get; set; }
        public Nullable<int> userTypeID { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> stateID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string emailID { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string profilePicture { get; set; }
        public Nullable<bool> emailConfirmed { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> cityid { get; set; }
        public string middleName { get; set; }
        public Nullable<int> titleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAuthentication> tblAuthentications { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual tblCity tblCity1 { get; set; }
        public virtual tblCity tblCity2 { get; set; }
        public virtual tblCity tblCity3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContactU> tblContactUs { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDonation> tblDonations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmailTemplateSave> tblEmailTemplateSaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblErrorlog> tblErrorlogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvent> tblEvents { get; set; }
        public virtual tblTitle tblTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubscribe> tblSubscribes { get; set; }
        public virtual tblState tblState { get; set; }
        public virtual tblUserType tblUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTestimonial> tblTestimonials { get; set; }
    }
}
